call z aqua
call z aura
call z axis
call z base
call z aurasqlite
call z auracharguess
call z axiscrypto
call z axisopenssl
call z axisidn
call z axisbzip2
call z axiszlib
call z core
call z npca2
call z app.install
call z app_core_hellomultiverse
call z app_core_bergedge
call z app_core_berghold
call z game_pacman
